---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: aquasec/scanner-cli
    tag: 3.2
    username: ((mustafaatakan-username))
    password: ((mustafaatakan-passwd))

inputs:
  - name: hello_hapi

run:
  path: hello_hapi/ci/scripts/run_security_scan.sh
