---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.12"


resources:
  - name: hello_hapi
    type: git
    source: &repo-source
      uri: https://github.com/matakan/hello_hapi
      branch: master

  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

  - name: docker-push
    type: docker-image
    source:
      repository: mustafaatakan/demo-cicd
      username: ((mustafaatakan-username))
      password: ((mustafaatakan-passwd))

  - name: k8s
    type: kubernetes
    source:
      kubeconfig: ((k8s_server))


jobs:
  - name: Install_dependencies
    plan:
      - get: hello_hapi
        trigger: true
      - get: dependency-cache

  - name: Run_tests
    plan:
      - get: hello_hapi
        trigger: true
        passed: [Install_dependencies]
      - get: dependency-cache
        passed: [Install_dependencies]
      - task: run the test suite
        file: hello_hapi/ci/tasks/run_tests.yml

  - name: Docker_Build
    public: false
    plan:
      - get: hello_hapi
        trigger: true
        passed: [Run_tests]
      - get: dependency-cache
        passed: [Run_tests]
      - put: docker-push
        params:
          build: hello_hapi

  - name: Security_scan
    plan:
      - get: hello_hapi
        trigger: true
        passed: [Docker_Build]
      - get: docker-push
        passed: [Docker_Build]
      - task: run security scan
#        file: hello_hapi/ci/tasks/run_security_scan.yml
        config:
         platform: linux

         image_resource:
           type: docker-image
           source:
             repository: aquasec/scanner-cli
             tag: 3.2
             username: ((mustafaatakan-username))
             password: ((mustafaatakan-passwd))

         inputs:
           - name: hello_hapi
           - name: docker-push

         run:
           path: scan -H http://aqua-server:8080 -U scanuser -P myscan7 --registry "Docker Hub" redis:latest

  - name: Deploy_Application
    public: false
    plan:
      - get: hello_hapi
        trigger: true
        passed:
          - "Security_scan"
      - put: k8s
        params:
#          kubectl: delete pods -l app=demo-cicd
          kubectl: apply -f hello_hapi/kubeResource.yml
          wait_until_ready: 300
#          kubeconfig_file: ./.kube/config
